### ISSUE TITLE
reflect: call of reflect.Value.Interface on zero Value

### ISSUE THREAD

**Issue by kennyjwilli** [pb33f/openapi-changes#167]
The openapi-changes console command is failing with a panic related to Go reflection. This issue started occurring recently after changes to our OpenAPI specification. Happy to provide any additional information to help debug. 

```
pnpm openapi-changes console ./ docs/nucleus-service/openapi.json

@@@@@@@   @@@@@@@   @@@@@@   @@@@@@   @@@@@@@@
@@@@@@@@  @@@@@@@@  @@@@@@@  @@@@@@@  @@@@@@@@
@@!  @@@  @@!  @@@      @@@      @@@  @@!
!@!  @!@  !@   @!@      @!@      @!@  !@!
@!@@!@!   @!@!@!@   @!@!!@   @!@!!@   @!!!:!
!!@!!!    !!!@!!!!  !!@!@!   !!@!@!   !!!!!:
!!:       !!:  !!!      !!:      !!:  !!:
:!:       :!:  !:!      :!:      :!:  :!:
 ::        :: ::::  :: ::::  :: ::::   ::
 :        :: : ::    : : :    : : :    :


🔗 https://pb33f.io/openapi-changes/
------------------------------------
openapi-changes version: 0.0.69 | compiled: Tue, 22 Oct 2024 14:03:15 UTC

  SPEC   5 commits extracted
  DONE   starting console...

panic: reflect: call of reflect.Value.Interface on zero Value

goroutine 1 [running]:
reflect.valueInterface({0x0?, 0x0?, 0x1049b029c?}, 0x7?)
	/opt/hostedtoolcache/go/1.23.2/x64/src/reflect/value.go:1486 +0xfc
reflect.Value.Interface(...)
	/opt/hostedtoolcache/go/1.23.2/x64/src/reflect/value.go:1481
github.com/pb33f/openapi-changes/tui.BuildSliceTreeNode[...]({0x104e0cc60, 0x14009f176d0?, 0x7?}, 0x14005d19e00?, {0x104ea9100, 0x14009f176c0}, {0x14006154e08, 0x5})
	/home/runner/work/openapi-changes/openapi-changes/tui/build_tree.go:282 +0x28c
github.com/pb33f/openapi-changes/tui.buildTreeNode(0x14005d19e00, {0x104ea9100, 0x14009f176c0})
	/home/runner/work/openapi-changes/openapi-changes/tui/build_tree.go:116 +0x36cc
github.com/pb33f/openapi-changes/tui.BuildTreeMapNode({0x104e7ca40?, 0x14003b4c828?, 0x0?}, 0x1400797fb00)
	/home/runner/work/openapi-changes/openapi-changes/tui/build_tree.go:298 +0x1b0
github.com/pb33f/openapi-changes/tui.buildTreeNode(0x1400797fa00, {0x104ea9a80, 0x14003b4c820})
	/home/runner/work/openapi-changes/openapi-changes/tui/build_tree.go:175 +0x2dbc
github.com/pb33f/openapi-changes/tui.DigIntoObject[...](0x1400797f480, 0x1400797fa00, {0x104ea9a80, 0x14007e58070?, 0x104ea9e00?})
	/home/runner/work/openapi-changes/openapi-changes/tui/build_tree.go:315 +0x100
github.com/pb33f/openapi-changes/tui.buildTreeNode(0x1400797f480, {0x104ea9e00, 0x14007e58000})
	/home/runner/work/openapi-changes/openapi-changes/tui/build_tree.go:96 +0x39cc
github.com/pb33f/openapi-changes/tui.BuildTreeModel({0x105012ef0?, 0x14005e13600?}, 0x14007e58000)
	/home/runner/work/openapi-changes/openapi-changes/tui/build_tree.go:35 +0xc0
github.com/pb33f/openapi-changes/tui.BuildTreeView(0x140000ba2a0?)
	/home/runner/work/openapi-changes/openapi-changes/tui/build_tree.go:20 +0x30
github.com/pb33f/openapi-changes/tui.BuildApplication({0x1400001e840, 0x5, 0x8}, {0x104dbc094, 0x6})
	/home/runner/work/openapi-changes/openapi-changes/tui/main_console.go:24 +0x4c
github.com/pb33f/openapi-changes/cmd.init.0.GetConsoleCommand.func1(0x140000d2308, {0x140000885e0, 0x2, 0x1049ae56f?})
	/home/runner/work/openapi-changes/openapi-changes/cmd/console.go:220 +0x584
github.com/spf13/cobra.(*Command).execute(0x140000d2308, {0x14000088580, 0x2, 0x2})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:985 +0x834
github.com/spf13/cobra.(*Command).ExecuteC(0x105746300)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/pb33f/openapi-changes/cmd.Execute({0x104dbc094?, 0x19?}, {0x104dbc800?, 0x1049bcf0e?}, {0x14000022560?, 0x140000021c0?})
	/home/runner/work/openapi-changes/openapi-changes/cmd/root.go:52 +0xa0
main.main()
	/home/runner/work/openapi-changes/openapi-changes/openapi-changes.go:29 +0x184
```

**Comment by daveshanley** [comment]
oh dear, this is a bug. 

The code uses reflection to build out a model to render the changes. So there is something in your spec that we have not seen before and not put a guard in place to check for a zero value before doing any work. 

Can you provide the spec? or a snippet of the spec that causes this? I will need it to build a test to validate the fix.

**Comment by kennyjwilli** [comment]
Hey @daveshanley. Thanks for the quick response 😄 Sure - the spec is publicly available here https://os.edge.deeporigin.io/data-hub/api/openapi.json.

**Comment by daveshanley** [comment]
this will be fixed in the next release

**Comment by daveshanley** [comment]
Fixed in `v0.0.71`
