### ISSUE TITLE
[feature] add support for asyncapi?

### ISSUE THREAD

**Issue by s01868** [pb33f/openapi-changes#173]
Hi, great tool. Our team are really interested in using it, but we also have [AsyncAPI specs](https://www.asyncapi.com/en) that need to be analysed for diff changes. 

I've tried it on a AsyncAPI spec, but getting the following error:

```
panic: runtime error: slice bounds out of range [:1] with capacity 0

goroutine 1 [running]:
github.com/pb33f/openapi-changes/cmd.runGitHistoryReport({0x140002b6240, 0x36}, {0x16f7732b5, 0x3a}, 0x1, 0x140002ca230, 0x140002ca2a0, {0x0, 0x0}, 0x1, ...)
        /home/runner/work/openapi-changes/openapi-changes/cmd/report.go:265 +0x650
github.com/pb33f/openapi-changes/cmd.GetReportCommand.func1(0x140002f0908, {0x14000289800, 0x2, 0x100db256f?})
        /home/runner/work/openapi-changes/openapi-changes/cmd/report.go:163 +0x730
github.com/spf13/cobra.(*Command).execute(0x140002f0908, {0x140002897a0, 0x3, 0x3})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:985 +0x834
github.com/spf13/cobra.(*Command).ExecuteC(0x101b4a300)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/pb33f/openapi-changes/cmd.Execute({0x1011c0094?, 0x19?}, {0x1011c0800?, 0x100dc0f0e?}, {0x140002a84a0?, 0x140000021c0?})
        /home/runner/work/openapi-changes/openapi-changes/cmd/root.go:52 +0xa0
main.main()
        /home/runner/work/openapi-changes/openapi-changes/openapi-changes.go:29 +0x184
```

Is this something you're interested to add in the future?

**Comment by daveshanley** [comment]
![Image](https://github.com/user-attachments/assets/99ddb2d4-0759-48cb-b69c-92fb1adba727)
