### ISSUE TITLE
Deadlock!

### ISSUE THREAD

**Issue by OllieTho** [pb33f/openapi-changes#25]
Hi!

I installed the openapi-changes package via npm and when I try to run a report or html report between two files I end up with the following deadlock error.

```
$ openapi-changes html-report merge/devtest.v1.yaml pr/devtest.v1.yaml

fatal error: all goroutines are asleep - deadlock!

goroutine 1 [chan send]:
github.com/pb33f/openapi-changes/model.SendProgressUpdate(...)
        /home/runner/work/openapi-changes/openapi-changes/model/progress.go:26
github.com/pb33f/openapi-changes/git.BuildCommitChangelog({0xc0000c7b28, 0x2, 0xc0000c7b38?}, 0x1?, 0x1?)
        /home/runner/work/openapi-changes/openapi-changes/git/read_local.go:149 +0x334
github.com/pb33f/openapi-changes/cmd.RunLeftRightHTMLReport({0xc0000aa078, 0x15}, {0xc0000aa090, 0x12}, 0x0?, 0x0?, 0x0?)
        /home/runner/work/openapi-changes/openapi-changes/cmd/html_report.go:325 +0x625
github.com/pb33f/openapi-changes/cmd.GetHTMLReportCommand.func1(0xc0001b6900?, {0xc00006e240, 0x2, 0x2?})
        /home/runner/work/openapi-changes/openapi-changes/cmd/html_report.go:175 +0x659
github.com/spf13/cobra.(*Command).execute(0xc0001b6900, {0xc00006e1e0, 0x2, 0x2})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x16ac500)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/pb33f/openapi-changes/cmd.Execute({0x1305ba8?, 0x0?}, {0x130da80?, 0x0?}, {0x1309e30?, 0xc000060000?})
        /home/runner/work/openapi-changes/openapi-changes/cmd/root.go:48 +0xaa
main.main()
        /home/runner/work/openapi-changes/openapi-changes/openapi-changes.go:26 +0x10e
```

I haven't been able to find any info related to the package that has helped me determine what is causing this.  The tool works when I generate a report when compared to a branch's git history, but I'm needing to compare files across branches.

Let me know if you've seen this issue before and what possible resolutions might be! Thanks!

**Comment by daveshanley** [comment]
Ah, this is a bug. Thank you for finding this. I’ll fix it ASAP!

**Comment by daveshanley** [comment]
I'm having some trouble re-creating the bug, can you provide the specs you're using for left/right comparison?

**Comment by OllieTho** [comment]
Sure thing! And thank you for your quick response!  GitHub doesn't support .yaml extensions so I just changed them to txt for uploading purposes.  The 'original' file is the left unchanged file and 'modified' should be the right and updated version.

Thanks again!

[devtest.v1-original.txt](https://github.com/pb33f/openapi-changes/files/10981722/devtest.v1-original.txt)
[devtest.v1-modified.txt](https://github.com/pb33f/openapi-changes/files/10981727/devtest.v1-modified.txt)

**Comment by daveshanley** [comment]
Cool, I will debug this as soon as I can.

**Comment by OllieTho** [comment]
@daveshanley Just checking to see if there were any status updates on this, thanks!

**Comment by OllieTho** [comment]
No worries! Thanks for keeping this in your queue! Hope you're feeling better!

**Comment by daveshanley** [comment]
`v0.0.19` Has this problem been fixed, I am sorry for the inconvenience - it was a silly mistake on my part. `html-report` should be fully operational again.

**Comment by OllieTho** [comment]
Thanks! I can confirm it's working on my end as well!

I'm seeing the same deadlock error when running it with the 'report' command as well.  Not sure if that is related, but thought I'd let you know!

**Comment by daveshanley** [comment]
Oh wow, yes. I need to do a full sweep on the CLI.

**Comment by OllieTho** [comment]
Hi @daveshanley ! I see there's been some commits related to this but the releases haven't had another build as of yet.  I was curious as to the status of this and if there's an expected timeline to rollout to the fixes?  Thanks!

**Comment by daveshanley** [comment]
I've published v0.0.20, sorry about the delay - I thought it had already gone out!

**Comment by OllieTho** [comment]
No worries! Looks like it's working great! Thank you for the responsiveness and quick turnaround!
