### ISSUE TITLE
Incorrect "cannot resolve reference..." error

### ISSUE THREAD

**Issue by WillGunn** [pb33f/openapi-changes#33]
I'm running the latest 0.0.21 release on windows, comparing two swagger files in summary mode like so: `.\bin\openapi-changes.exe summary .\v1_latest.json .\v2_latest.json`
the command prints the following:

```
openapi-changes version: 0.0.21 | compiled: 2023-04-20T15:53:45Z

  ERROR   Stopped: Error thrown when comparing: cannot resolve reference `#/components/schemas/ResourceList[InsuranceResource]`, it's missing: $.components.schemas.ResourceList[InsuranceResource] [36847:13]


fatal error: all goroutines are asleep - deadlock!

goroutine 1 [chan send]:
github.com/pb33f/openapi-changes/model.SendProgressError(...)
        /home/runner/work/openapi-changes/openapi-changes/model/progress.go:43
github.com/pb33f/openapi-changes/git.BuildCommitChangelog({0xc00a9adba0, 0x2, 0xc0000b9bb0?}, 0x1?, 0x1?)
        /home/runner/work/openapi-changes/openapi-changes/git/read_local.go:167 +0xc45
github.com/pb33f/openapi-changes/cmd.runLeftRightSummary({0xc0000240c0, 0x10}, {0xc0000240f0, 0x10}, 0x0?, 0x0?)
        /home/runner/work/openapi-changes/openapi-changes/cmd/summary.go:211 +0x5ec
github.com/pb33f/openapi-changes/cmd.GetSummaryCommand.func1(0xc000004600?, {0xc000112220, 0x2, 0x2?})
        /home/runner/work/openapi-changes/openapi-changes/cmd/summary.go:162 +0x53b
github.com/spf13/cobra.(*Command).execute(0xc000004600, {0xc0001121c0, 0x2, 0x2})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x117d640)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/pb33f/openapi-changes/cmd.Execute({0xdc2194?, 0x0?}, {0xdc8960?, 0x0?}, {0xdc4250?, 0xc00006c000?})
        /home/runner/work/openapi-changes/openapi-changes/cmd/root.go:48 +0xaa
main.main()
        /home/runner/work/openapi-changes/openapi-changes/openapi-changes.go:26 +0x10e

goroutine 18 [chan send]:
github.com/pb33f/openapi-changes/cmd.GetSummaryCommand.func1.1(0xc00011c060, 0xc00011c0c0)
        /home/runner/work/openapi-changes/openapi-changes/cmd/summary.go:91 +0x4b9
created by github.com/pb33f/openapi-changes/cmd.GetSummaryCommand.func1
        /home/runner/work/openapi-changes/openapi-changes/cmd/summary.go:161 +0x50c
``` 

Based on the line number I believe it is erroring on the 2nd file which has the correct schema and reference path as shown:
![Screenshot 2023-04-25 105234](https://user-images.githubusercontent.com/3417781/234317936-1a895ad2-ee3a-4ca9-a15d-9cbf6f2007b4.png)

Let me know if you need additional information.

**Comment by WillGunn** [comment]
@daveshanley same error on .22.  Let me see if I can cut these files down so I can upload the files for reproduction.
```
openapi-changes version: 0.0.22 | compiled: 2023-04-27T12:55:57Z

  ERROR   Stopped: Error thrown when comparing: component '#/components/schemas/ResourceList[PlanResource]' does not exist in the specification


fatal error: all goroutines are asleep - deadlock!

goroutine 1 [chan send]:
github.com/pb33f/openapi-changes/model.SendProgressError(...)
        /home/runner/work/openapi-changes/openapi-changes/model/progress.go:43
github.com/pb33f/openapi-changes/git.BuildCommitChangelog({0xc006787ba0, 0x2, 0xc000149bb0?}, 0x1?, 0x1?)
        /home/runner/work/openapi-changes/openapi-changes/git/read_local.go:167 +0xc45
github.com/pb33f/openapi-changes/cmd.runLeftRightSummary({0xc000126090, 0x10}, {0xc0001260c0, 0x10}, 0x0?, 0x0?)
        /home/runner/work/openapi-changes/openapi-changes/cmd/summary.go:214 +0x5ec
github.com/pb33f/openapi-changes/cmd.GetSummaryCommand.func1(0xc000230300?, {0xc00007a260, 0x2, 0x2?})
        /home/runner/work/openapi-changes/openapi-changes/cmd/summary.go:165 +0x55b
github.com/spf13/cobra.(*Command).execute(0xc000230300, {0xc00007a200, 0x2, 0x2})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x1bb97e0)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/pb33f/openapi-changes/cmd.Execute({0x17bae94?, 0x0?}, {0x17c1680?, 0x0?}, {0x17bcf50?, 0xc00006c000?})
        /home/runner/work/openapi-changes/openapi-changes/cmd/root.go:48 +0xaa
main.main()
        /home/runner/work/openapi-changes/openapi-changes/openapi-changes.go:26 +0x10e

goroutine 5 [chan send]:
github.com/pb33f/openapi-changes/cmd.GetSummaryCommand.func1.1(0xc00008e060, 0xc00008e0c0)
        /home/runner/work/openapi-changes/openapi-changes/cmd/summary.go:94 +0x4b9
created by github.com/pb33f/openapi-changes/cmd.GetSummaryCommand.func1
        /home/runner/work/openapi-changes/openapi-changes/cmd/summary.go:164 +0x52c
```

**Comment by WillGunn** [comment]
@daveshanley this is a barebones reproduction of the issue.
[v1_latest.json.txt](https://github.com/pb33f/openapi-changes/files/11344364/v1_latest.json.txt)
[v2_latest.json.txt](https://github.com/pb33f/openapi-changes/files/11344365/v2_latest.json.txt)

**Comment by daveshanley** [comment]
Thank you for this, it really helped! The issue was a simple one, too many errors being sent (in this case, 4 errors are generated) the code was only expecting one error, so when the rest tried to get sent, the application locked up because there was nothing listening for those remaining errors.

Let me know how `v0.0.23` works for you.

**Comment by daveshanley** [comment]
Closing for now, let me know if it re-appears.

**Comment by WillGunn** [comment]
Actually nevermind for that, but I think thats another bug, I forgot I renamed the v2 file to .json.txt and re-reran the command with it as .json (which didn't exist) and so I think it spins forever if the file does not exist.

**Comment by daveshanley** [comment]
This looks like a very different problem. It's actually an issue with `libopenapi` failing to lookup the resource. The culprit I think is the way the types are structured. `#/components/schemas/ResourceList[InsuranceResource]` for example... this is an unusual approach, it's confusing the tool because the square brackets generally should not be there.

I added a bug to track this: 

https://github.com/pb33f/libopenapi/issues/112

**Comment by WillGunn** [comment]
Hmm, we are using a custom TypeName filter in Swashbuckle.Aspnetcore,
```c#
public static string GetTypeName(Type type)
        {
            if (type.IsGenericType)
            {
                var paramTypeList = new List<string>();
                foreach (var genericParam in type.GenericTypeArguments)
                {
                    paramTypeList.Add(GetTypeName(genericParam));
                }

                var genericType = string.Join(",", paramTypeList);
                var name = type.Name.Substring(0, type.Name.IndexOf("`"));

                return $"{name}[{genericType}]";
            }
            else
            {
                return type.Name;
            }
        }
``` 
and it doesn't cause issues in the rest of our tools, but I do see that pasting the file into https://editor-next.swagger.io/ complains about the [] symbols in the component keys (regex `^[a-zA-Z0-9\.\-_]+$` ).

Looking at it, that line is in the spec now, not sure I agree with it though.  There isn't really a good way to represent generics using only alphanumeric and .-_

**Comment by WillGunn** [comment]
Looking into this more, we used this code back with swagger/openapi 2.0, and looking at the spec, there were no key limitations specified from what I can tell, so the addition of that was a breaking change from 2.0 to 3.0, but it seems most tools don't impose that 3.0 limitation.
